version: '3'

services:
  app:
    build: .
    restart: on-failure
    ports:
      - "8001:8001"
    environment:
      POSTGRES_SERVER: db
      POSTGRES_USER: fast_user
      POSTGRES_PASSWORD: magical_password
      POSTGRES_DB: example_db
      PYTHONUNBUFFERED: 1
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: fast_user
      POSTGRES_PASSWORD: magical_password
      POSTGRES_DB: example_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fast_user -d example_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
